from .common import case


CASES = [
    case(
        name="cd_pwd",
        must_contain=[
            "shelltest: cd begin",
            "cd: /usr/bin",
            "shelltest: cd end",
            "shelltest: pwd begin",
            "pwd: /usr/bin",
            "shelltest: pwd end",
            "shelltest: ls begin",
            "ext2 directory: usr/bin",
            "shelltest: ls end",
            "shelltest: fsread_rel begin",
            "fsread: hello.elf",
            "shelltest: fsread_rel end",
            "shelltest: cat_rel begin",
            ";; SmallOS compiler demo output",
            "MOV AX, 1",
            "INT 0x80",
            "shelltest: cat_rel end",
            "shelltest: touch_rel begin",
            "touch: ../../var/tmp/LOCAL.TXT",
            "shelltest: touch_rel end",
            "shelltest: fsread_touch_rel begin",
            "fsread: ../../var/tmp/LOCAL.TXT  0 bytes",
            "shelltest: fsread_touch_rel end",
            "shelltest: runelf_rel begin",
            "argv[0] = \"hello\"",
            "argv[1] = \"alpha\"",
            "argv[2] = \"beta\"",
            "shelltest: runelf_rel end",
            "shelltest: cd_root begin",
            "cd: /",
            "shelltest: cd_root end",
            "shelltest: pwd_root begin",
            "pwd: /",
            "shelltest: pwd_root end",
            "shelltest: ls_root begin",
            "ext2 root directory:",
            "shelltest: ls_root end",
        ],
        timeout=60.0,
    )
]
