from .common import case


CASES = [
    case(
        name="cp_mv",
        must_contain=[
            "shelltest: compiler_demo begin",
            "compiler_demo PASS",
            "shelltest: compiler_demo end",
            "shelltest: mkdir_var_tmp begin",
            "mkdir: var/tmp",
            "shelltest: mkdir_var_tmp end",
            "shelltest: mkdir_work begin",
            "shelltest: mkdir_work end",
            "shelltest: cp begin",
            "cp: var/tmp/compiler.out -> var/tmp/compiler.copy",
            "shelltest: cp end",
            "shelltest: fsread_copy begin",
            "fsread: var/tmp/compiler.copy",
            "shelltest: fsread_copy end",
            "shelltest: mv begin",
            "mv: var/tmp/compiler.copy -> var/tmp/compiler.moved",
            "shelltest: mv end",
            "shelltest: fsread_moved begin",
            "fsread: var/tmp/compiler.moved",
            "shelltest: fsread_moved end",
            "shelltest: cp_dir begin",
            "cp: var/tmp/compiler.out -> var/tmp/WORK",
            "shelltest: cp_dir end",
            "shelltest: fsread_dir_copy begin",
            "fsread: var/tmp/WORK/compiler.out",
            "shelltest: fsread_dir_copy end",
            "shelltest: rm_dir begin",
            "rm: var/tmp/WORK/compiler.out",
            "shelltest: rm_dir end",
            "shelltest: fsread_dir_removed begin",
            "ext2: not found: var/tmp/WORK/compiler.out",
            "fsread: load failed",
            "shelltest: fsread_dir_removed end",
            "shelltest: mv_dir begin",
            "mv: var/tmp/compiler.moved -> var/tmp/WORK",
            "shelltest: mv_dir end",
        ],
        timeout=60.0,
    )
]
