from .common import case


CASES = [
    case(
        name="badptrprobe",
        command="runelf apps/tests/badptrprobe",
        must_contain=[
            "badptrprobe start",
            "write unmapped buffer: PASS",
            "open unmapped path: PASS",
            "exec unmapped argv: PASS",
            "open fixture: PASS",
            "fread unmapped buffer: PASS",
            "close fixture: PASS",
            "stat unmapped size out: PASS",
            "stat unmapped dir out: PASS",
            "terminal size bad rows: PASS",
            "terminal size bad cols: PASS",
            "boundary heap page: PASS",
            "write page-cross buffer: PASS",
            "read page-cross buffer: PASS",
            "open page-cross path: PASS",
            "writefd page-cross buffer: PASS",
            "stat page-cross size out: PASS",
            "terminal size page-cross rows: PASS",
            "dirlist page-cross out: PASS",
            "display info page-cross out: PASS",
            "fsinfo page-cross out: PASS",
            "fsmap page-cross request: PASS",
            "fsmap page-cross states: PASS",
            "poll overflow nfds: PASS",
            "poll page-cross fds: PASS",
            "epoll create: PASS",
            "epoll wait too many: PASS",
            "epoll wait bad events: PASS",
            "epoll ctl page-cross event: PASS",
            "epoll wait page-cross events: PASS",
            "close epoll: PASS",
            "timerfd create: PASS",
            "timerfd page-cross new: PASS",
            "timerfd page-cross old: PASS",
            "close timerfd: PASS",
            "signalfd page-cross mask: PASS",
            "badptrprobe PASS",
        ],
        timeout=60.0,
    )
]
