from .common import case


CASES = [
    case(
        "busybox smoke",
        "selftest",
        must_contain=[
            "selftest: busybox true woke",
            "selftest: busybox false woke",
            "busybox-echo-ok",
            "selftest: bin sh woke",
            "selftest: busybox ash woke",
            "selftest: busybox pwd woke",
            "selftest: busybox cat woke",
            "selftest: busybox ls woke",
            "selftest: busybox test woke",
            "selftest: busybox expr woke",
            "selftest: busybox grep woke",
            "selftest: busybox sed woke",
            "selftest: busybox awk woke",
            "selftest: busybox df woke",
            "selftest: busybox du woke",
            "selftest: busybox free woke",
            "selftest: busybox ps woke",
            "selftest: busybox date woke",
            "selftest: busybox ip neigh woke",
            "selftest: busybox hostname woke",
            "selftest: busybox dnsdomainname woke",
            "selftest: busybox ipcalc woke",
            "selftest: busybox netstat route woke",
            "selftest: busybox netstat woke",
            "selftest: busybox nslookup localhost woke",
            "selftest: busybox arp woke",
            "selftest: busybox ftpget usage woke",
            "selftest: busybox ftpput usage woke",
            "selftest: busybox tftp usage woke",
            "selftest: busybox tcpsvd usage woke",
            "selftest: busybox udpsvd usage woke",
            "selftest: busybox tftpd usage woke",
            "selftest: busybox fallback grep woke",
            "selftest: busybox dev null woke",
            "selftest: busybox dd zero woke",
            "selftest: busybox od woke",
            "selftest: busybox hexdump woke",
            "busybox-ls-proof-xyz",
            "selftest: busybox ls proof woke",
            "selftest: busybox mkdir woke",
            "selftest: busybox rmdir woke",
            "selftest: busybox mount prep woke",
            "selftest: busybox mount proc woke",
            "selftest: busybox mount list woke",
            "selftest: busybox mount read woke",
            "selftest: busybox umount proc woke",
            "selftest: busybox mount cleanup woke",
            "selftest: busybox rm woke",
            "selftest: busybox basename woke",
            "selftest: busybox dirname woke",
            "selftest: busybox env woke",
            "selftest: busybox printenv woke",
            "selftest: busybox whoami woke",
            "selftest: busybox uname woke",
            "selftest: busybox tty woke",
            "selftest: busybox seq woke",
            "selftest: busybox sleep woke",
            "selftest: busybox usleep woke",
            "selftest: busybox head woke",
            "selftest: busybox wc woke",
            "busybox-cut-ok",
            "BUSYBOX-TR-OK",
            "busybox-printf-ok",
            "selftest: busybox cp woke",
            "selftest: busybox chmod woke",
            "selftest: busybox chown woke",
            "selftest: busybox chgrp woke",
            "selftest: busybox tar create woke",
            "selftest: busybox tar list woke",
            "selftest: busybox realpath woke",
            "selftest: busybox find prep woke",
            "busybox-find-target",
            "selftest: busybox find type woke",
            "selftest: busybox cmp woke",
            "selftest: busybox diff woke",
            "busybox-sort-ok",
            "busybox-uniq-ok",
            "busybox-xargs-ok",
            "busybox-xargs0-ok",
            "busybox-tee-ok",
            "selftest: busybox tee cat woke",
            "selftest: busybox sync woke",
            "selftest: busybox mv prep woke",
            "selftest: busybox mv woke",
            "selftest: busybox touch woke",
            "selftest: busybox stat woke",
            "busybox-stat-format:/tmp/busybox-touch.txt",
            "selftest: busybox stat fs woke",
            "selftest: busybox id woke",
            "selftest: busybox kill missing woke",
            "busybox-checksum-ok",
            "d3de090623d4fd10a78178979f34af3b",
            "161fc5b0f3d18464fb964d6653cf7c5b2a7a3fd7",
            "36fd0813d56da73f3f1866aefaacea69d5a099201922ba7fa33ee8e6663869a2",
            "selftest: busybox gzip prep woke",
            "selftest: busybox gzip woke",
            "selftest: busybox gunzip woke",
            "selftest: busybox gzip cat woke",
            "selftest: busybox tar gz prep woke",
            "selftest: busybox tar gzip woke",
            "selftest: busybox tar autodetect woke",
            "tmp/busybox-gzip.txt",
            "selftest: busybox ls dir prep woke",
            "busybox-lsdir/",
            "busybox-ls-sort-ok",
            "selftest: busybox ls sort woke",
            "selftest: busybox ln hard woke",
            "selftest: busybox link applet woke",
            "selftest: busybox ln cat woke",
            "/tmp/busybox-sum.txt",
            "selftest: busybox ln symlink woke",
            "selftest: busybox readlink woke",
            "selftest: busybox symlink cat woke",
            "selftest: busybox mkfifo woke",
            "selftest: busybox mknod woke",
            "selftest: busybox stat fifo woke",
            "selftest: busybox stat char woke",
            "selftest: busybox unlink woke",
        ],
        timeout=60.0,
    ),
]
