from .common import case


CASES = [
    case(
        "busybox smoke",
        "selftest",
        must_contain=[
            "selftest: busybox true woke",
            "selftest: busybox false woke",
            "busybox-echo-ok",
            "selftest: bin sh woke",
            "selftest: busybox ash woke",
            "selftest: busybox pwd woke",
            "selftest: busybox cat woke",
            "selftest: busybox ls woke",
            "selftest: busybox test woke",
            "selftest: busybox expr woke",
            "selftest: busybox grep woke",
            "selftest: busybox sed woke",
            "selftest: busybox awk woke",
            "selftest: busybox df woke",
            "selftest: busybox du woke",
            "selftest: busybox free woke",
            "selftest: busybox ps woke",
            "selftest: busybox date woke",
            "selftest: busybox fallback grep woke",
            "selftest: busybox dev null woke",
            "selftest: busybox dd zero woke",
            "selftest: busybox od woke",
            "selftest: busybox hexdump woke",
            "busybox-ls-proof-xyz",
            "selftest: busybox ls proof woke",
            "selftest: busybox mkdir woke",
            "selftest: busybox rmdir woke",
            "selftest: busybox rm woke",
            "selftest: busybox basename woke",
            "selftest: busybox dirname woke",
            "selftest: busybox env woke",
            "selftest: busybox printenv woke",
            "selftest: busybox whoami woke",
            "selftest: busybox uname woke",
            "selftest: busybox tty woke",
            "selftest: busybox seq woke",
            "selftest: busybox sleep woke",
            "selftest: busybox usleep woke",
            "selftest: busybox head woke",
            "selftest: busybox wc woke",
            "busybox-cut-ok",
            "BUSYBOX-TR-OK",
            "busybox-printf-ok",
            "selftest: busybox cp woke",
            "selftest: busybox chmod woke",
            "selftest: busybox chown woke",
            "selftest: busybox tar create woke",
            "selftest: busybox tar list woke",
            "selftest: busybox realpath woke",
            "selftest: busybox find prep woke",
            "busybox-find-target",
            "selftest: busybox cmp woke",
            "selftest: busybox diff woke",
            "busybox-sort-ok",
            "busybox-uniq-ok",
            "busybox-xargs-ok",
            "busybox-tee-ok",
            "selftest: busybox tee cat woke",
            "selftest: busybox sync woke",
            "selftest: busybox mv prep woke",
            "selftest: busybox mv woke",
            "selftest: busybox touch woke",
            "selftest: busybox stat woke",
            "selftest: busybox id woke",
            "selftest: busybox kill missing woke",
            "selftest: busybox unlink woke",
        ],
        timeout=60.0,
    ),
]
