from .common import case


CASES = [
    case(
        "compatprobe",
        "usr/libexec/tests/compatprobe",
        must_contain=[
            "compatprobe start",
            "setbuf noop: PASS",
            "stat timespec: PASS",
            "ftruncate shrink: PASS",
            "ftruncate grow: PASS",
            "futimens set: PASS",
            "chmod set: PASS",
            "chown set: PASS",
            "utimes set: PASS",
            "utimensat set: PASS",
            "hard link create: PASS",
            "hard link nlink: PASS",
            "readlink target: PASS",
            "lstat symlink: PASS",
            "stat symlink follows: PASS",
            "utimensat missing: PASS",
            "fnmatch bracket: PASS",
            "ioctl winsize: PASS",
            "chmod missing: PASS",
            "mknod char: PASS",
            "mkfifo node: PASS",
            "statfs root: PASS",
            "statfs proc: PASS",
            "statvfs root: PASS",
            "sysinfo basic: PASS",
            "stat bin sh: PASS",
            "stat proc dir: PASS",
            "stat dev null: PASS",
            "proc meminfo read: PASS",
            "proc self status: PASS",
            "opendir proc: PASS",
            "proc lists meminfo: PASS",
            "opendir dev: PASS",
            "dev lists null: PASS",
            "open dev null: PASS",
            "read dev zero: PASS",
            "fcntl dupfd: PASS",
            "open dev fd 1: PASS",
            "root passwd uid: PASS",
            "getgrouplist root: PASS",
            "getsid self: PASS",
            "sync noop: PASS",
            "sigaction stub: PASS",
            "compatprobe PASS",
        ],
    ),
]
