from .common import case


CASES = [
    case(
        "compatprobe",
        "usr/libexec/tests/compatprobe",
        must_contain=[
            "compatprobe start",
            "setbuf noop: PASS",
            "stat timespec: PASS",
            "ftruncate shrink: PASS",
            "ftruncate grow: PASS",
            "futimens set: PASS",
            "chmod set: PASS",
            "chown set: PASS",
            "utimes set: PASS",
            "utimensat set: PASS",
            "hard link create: PASS",
            "hard link nlink: PASS",
            "readlink target: PASS",
            "lstat symlink: PASS",
            "stat symlink follows: PASS",
            "utimensat missing: PASS",
            "fnmatch bracket: PASS",
            "ioctl winsize: PASS",
            "chmod missing: PASS",
            "mknod char: PASS",
            "mkfifo node: PASS",
            "statfs root: PASS",
            "statfs proc: PASS",
            "statvfs root: PASS",
            "sysinfo basic: PASS",
            "stat bin sh: PASS",
            "stat proc dir: PASS",
            "stat dev null: PASS",
            "proc meminfo read: PASS",
            "proc self status: PASS",
            "opendir proc: PASS",
            "proc lists meminfo: PASS",
            "proc lists net: PASS",
            "proc lists self: PASS",
            "opendir proc net: PASS",
            "proc net lists tcp: PASS",
            "opendir dev: PASS",
            "dev lists null: PASS",
            "dev lists urandom: PASS",
            "dev lists fd: PASS",
            "dev lists pts: PASS",
            "opendir dev fd: PASS",
            "dev fd lists 0: PASS",
            "opendir dev pts: PASS",
            "open dev null: PASS",
            "read dev zero: PASS",
            "fcntl dupfd: PASS",
            "open dev fd 1: PASS",
            "mempcpy helper: PASS",
            "memrchr helper: PASS",
            "stpcpy helper: PASS",
            "stpncpy helper: PASS",
            "strcasestr helper: PASS",
            "strchrnul helper: PASS",
            "strsep helper: PASS",
            "strsignal term: PASS",
            "strverscmp basic: PASS",
            "fdatasync wrapper: PASS",
            "mkdtemp helper: PASS",
            "ttyname_r stdout: PASS",
            "wait3 wrapper: PASS",
            "clearenv helper: PASS",
            "root passwd uid: PASS",
            "getgrouplist root: PASS",
            "getrlimit nofile: PASS",
            "getsid self: PASS",
            "sync noop: PASS",
            "sigaction stub: PASS",
            "compatprobe PASS",
        ],
    ),
]
