from .common import case


CASES = [
    case(
        "mountprobe",
        "usr/libexec/tests/mountprobe",
        must_contain=[
            "mountprobe start",
            "mounts root line: PASS",
            "mounts proc line: PASS",
            "mounts dev line: PASS",
            "statfs root ext2: PASS",
            "statfs proc: PASS",
            "statfs dev: PASS",
            "fstatfs proc: PASS",
            "fstatfs dev: PASS",
            "mount invalid type: PASS",
            "mount root busy: PASS",
            "mount dynamic gated: PASS",
            "mkdir proc mountpoint: PASS",
            "mount proc dynamic: PASS",
            "mounts dynamic proc line: PASS",
            "statfs dynamic proc: PASS",
            "dynamic proc meminfo: PASS",
            "open dynamic proc meminfo: PASS",
            "umount dynamic proc busy: PASS",
            "umount dynamic proc: PASS",
            "dynamic proc removed: PASS",
            "statfs proc target ext2: PASS",
            "rmdir proc mountpoint: PASS",
            "mkdir dev mountpoint: PASS",
            "mount dev dynamic: PASS",
            "mounts dynamic dev line: PASS",
            "open dynamic dev null: PASS",
            "fstatfs dynamic dev: PASS",
            "umount dynamic dev: PASS",
            "rmdir dev mountpoint: PASS",
            "umount root busy: PASS",
            "umount proc busy: PASS",
            "umount invalid target: PASS",
            "mountprobe PASS",
        ],
    ),
]
